# -*- coding: utf-8 -*-
"""OSS_2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16H1xrhJ23SMyrbfMy8wB9VeOGzEUAs17
"""

import pandas as pd
import numpy as np
# CSV 파일 경로를 변수에 저장합니다.
file_path = '/home/2019_kbo_for_kaggle_v2.csv'

# read_csv() 함수를 사용하여 CSV 파일을 데이터프레임으로 불러옵니다.
df = pd.read_csv(file_path)
# 데이터프레임 확인

print("----------- OSS Project2 -----------")
print("--- 컴퓨터공학과 12191823 정찬우 ---")
print("------------------------------------")
print("** Problem : 2-1 **")
print("** Problem : 2-1-1 **")

arr = [2015,2016,2017,2018]
for i in arr:

  df2 = df[df['year'] == i] # 2015~2018년까지의 데이터
  print(i,"년도 Stat")
  print("안타 Top 10:")
  print((df2.sort_values(ascending=False, by='H').batter_name.head(10))) #1
  print("타율 Top 10:")
  print((df2.sort_values(ascending=False, by='avg').batter_name.head(10))) #1
  print("홈런 Top 10:")
  print((df2.sort_values(ascending=False, by='HR').batter_name.head(10))) #1
  print("출루율 Top 10:")
  print((df2.sort_values(ascending=False, by='OBP').batter_name.head(10))) #1


print("------------------------------------")
print("** Problem : 2-1-2 **")

arr = ['포수','1루수','2루수','3루수','유격수','좌익수','중견수','우익수']
df3 = df[df['year'] == 2018]
df3 = df3.sort_values(by='war')
for i in arr:
  print(i,"Position's WAR Top 1 Player ")
  df4 = df3[df3['cp'] == i]

  print(df4.sort_values(ascending=False, by='war').head(1).batter_name)
  #print(df4.sort_values(ascending=False, by='war').war.head())
print("------------------------------------")
print("** Problem : 2-1-3 **")
arr = ['R','H','HR','RBI','SB','war','avg','OBP','SLG']
s1 = pd.Series([0,0,0,0,0,0,0,0,0], index = arr)

for i in arr:
  s1[i] = df[i].corr(df['salary'])
print("연봉과 상관 관계가 큰 요소 : ",s1.sort_values(ascending=False).head(1))

print("------------------------------------")
print("** Problem : 2-2 **")